/**
 * scripts/migrate.ts — apply pending Drizzle migrations to the SQLite database.
 *
 * Usage:
 *   pnpm db:migrate
 *
 * This script is intentionally thin. It opens the database with the same
 * client settings as lib/db/client.ts and runs migrate() from drizzle-orm.
 * The migration files in lib/db/migrations/ are generated by `pnpm db:generate`.
 */

import fs from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";

const dbPath = process.env.DATABASE_PATH ?? "./data/db.sqlite";

// Ensure the data directory exists before opening the database.
const dir = path.dirname(path.resolve(dbPath));
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

const sqlite = new Database(dbPath);
sqlite.pragma("journal_mode = WAL");
sqlite.pragma("foreign_keys = ON");

const db = drizzle(sqlite);

const migrationsFolder = path.resolve("lib/db/migrations");

console.log(`Running migrations from ${migrationsFolder} against ${dbPath} ...`);
migrate(db, { migrationsFolder });
console.log("Migrations complete.");

sqlite.close();
